// <auto-generated />
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250612094817_testData2")]
    partial class testData2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("API.Entity.Product", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("Stock")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Description for Product 1",
                            ImageUrl = "1.jpg",
                            IsActive = true,
                            Name = "Iphone 15",
                            Price = 70000m,
                            Stock = 100
                        },
                        new
                        {
                            Id = 2,
                            Description = "Description for Product 2",
                            ImageUrl = "https://example.com/product2.jpg",
                            IsActive = true,
                            Name = "Iphone 15 Pro Max",
                            Price = 95000m,
                            Stock = 50
                        },
                        new
                        {
                            Id = 3,
                            Description = "Description for Product 3",
                            ImageUrl = "https://example.com/product3.jpg",
                            IsActive = true,
                            Name = "Samsung Galaxy S23",
                            Price = 80000m,
                            Stock = 75
                        },
                        new
                        {
                            Id = 4,
                            Description = "Description for Product 4",
                            ImageUrl = "https://example.com/product4.jpg",
                            IsActive = true,
                            Name = "Google Pixel 8",
                            Price = 60000m,
                            Stock = 120
                        },
                        new
                        {
                            Id = 5,
                            Description = "Description for Product 5",
                            ImageUrl = "https://example.com/product5.jpg",
                            IsActive = true,
                            Name = "OnePlus 11",
                            Price = 55000m,
                            Stock = 80
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
